core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

gallery/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^(?P<page_number>\d+)/$', views.gallery, name='gallery'),
    url(r'^$', views.gallery, name='gallery'),
    # ex: /polls/5/
    #url(r'^([0-9]+)/(\d+)/$', views.album, name='album'),
    url(r'^(?P<page_number>\d+)/album/(?P<object_id>\d+)/$', views.album, name='album'),
    #url(r'^album/(?P<object_id>\d]+)/$', views.album, name='album'),
    #url(r'^album/([0-9]+)/$', views.album, name='album'),
    # ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

myfirst/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from views import hello, index

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello),
    url(r'^core/', include('core.urls', namespace="core")),
    url(r'^gallery/', include('gallery.urls')),
    #url(r'^about/', include('django.contrib.flatpages.urls')),
    url(r'^$', index),
]

core/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):         # __unicode__ on Python 2; __str__ on Python 3
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):              # __unicode__ on Python 2
        return self.choice_text

gallery/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models import permalink
from gallery.fields import ThumbnailImageField


class Album(models.Model):
    name = models.CharField(max_length=30, verbose_name='Название альбома транслитом')
    title = models.CharField(max_length=50, verbose_name='Название альбома')
    description = models.TextField(blank=True, verbose_name='Описание альбома')

    class Meta:
        verbose_name = 'Альбом'
        verbose_name_plural = 'альбомы'
        ordering = ['name']



    def __unicode__(self):
        return self.name


    #def get_absolute_url(self):
    #   return ('item_detail', None, {'object_id': self.id})

class Photo (models.Model):
    item = models.ForeignKey(Album)
    title = models.CharField(max_length=100, verbose_name='Название фото')
    image = ThumbnailImageField(upload_to='static/photos')
    caption = models.TextField(blank=True, verbose_name='Описание фото')

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'фотографии'
        ordering = ['title']

    def __unicode__(self):
        return self.title


    #def get_absolute_url(self):
    #   return reverse('album', args=[str(self.id)])

core/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import Http404

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader

from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'core/index.html', context) #'core/index.html' - 'APP_DIRS': True


def hello(request):
    return HttpResponse('Hello world')



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'core/detail.html', {'question': question}) #'core/detail.html - 'APP_DIRS': True'


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'core/results.html', {'question': question}) #'core/results.html - 'APP_DIRS': True


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'core/detail.html', {
            'question': p,
            'error_message': "Вы не сделали выбор.",
        }) #'core/detail.html' - 'APP_DIRS': True
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('core:results', args=(p.id,)))

gallery/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render_to_response, render, redirect
from django.core.exceptions import ObjectDoesNotExist
from gallery.models import Album, Photo
from django.core.paginator import Paginator, InvalidPage
#from django.http import HttpResponse, request


# Create your views here.
def gallery(request, page_number=1):
    all_albums = Album.objects.all()
    current_page = Paginator(all_albums, 2)
    try:
        item_list = current_page.page(page_number)
    except InvalidPage:
        return redirect('/gallery/1/', page_number = 1)

    return render(request, 'gallery/index.tpl', {'item_list':item_list, 'page_number':page_number})

def album(request, object_id, page_number=1):
    try:
        photos_list = Album.objects.get( pk=object_id)

    except IndentationError:
        photos_list = Album.objects.get( pk=1)
    except ObjectDoesNotExist:
        photos_list = Album.objects.get( pk=1)

    count = photos_list.photo_set.count()
    context = dict()
    context['object'] = photos_list
    photos_rows = []
    more_one_line = False
    #photo_last_line = False
    #photo_in_last_line = []
    photo_in_row = 3
    if count > photo_in_row:
        cnt = count/photo_in_row
        more_one_line = True
        for i in range(1, cnt+1):
            photos_rows.append(i*photo_in_row)


        #if count%photo_in_row:
        #   photo_last_line=True
        #   for i in range(cnt*photo_in_row, count):
        #       photo_in_last_line.append(i+1)
    context['photos_rows'] = photos_rows
    context['more_one_line'] = more_one_line
    context['page_number'] = page_number
    #context['photo_last_line'] = photo_last_line
    #context['photo_in_last_line'] = photo_in_last_line


    return render(request, 'gallery/album.tpl', context)

myfirst/views.py
from django.shortcuts import render

from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello world")

def index(request):
    
    return render(request, 'index.html')

# Create your views here.

templates/core/detail.html
{% extends 'index.html'%}

{%block index%}
<h2>{{ question.question_text }}</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'core:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Голосовать" />
</form>
{%endblock%}

templates/core/index.html
{% extends 'index.html'%}
{%block index%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'core:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No core are available.</p>
{% endif %}
{%endblock%}

templates/core/results.html
{% extends 'index.html'%}
{%block index%}
<h2>{{ question.question_text }}</h2>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'core:detail' question.id %}">Голосовать снова?</a>
{%endblock%}

templates/index.html
{%load staticfiles%}
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Gallery - {% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static "css/style.css"%}" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li class="active">
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li>
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="/about/">About</a>
				</li>
				<li>
					<a href="/contact/">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="adbox">
		<div class="clearfix">
			<img src="{% static "images/box.png" %}" alt="Img" height="342" width="368">
			<div>
			    <h1>Hi!</h1>
                <span><a href="index.html" class="btn">Try It Now!</a></span>

			</div>
		</div>
	</div>
	<div id="contents">
		<div id="tagline" class="clearfix">
			<h1>Design With Simplicity.</h1>
			{%block index%}{%endblock%}
			{%block content%}{%endblock%}
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a>
				<a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a>
				<a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a>
				<a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/index1.html
<!DOCTYPE html>
<html >

<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="servi" />

	<title>Неназванный 1</title>
</head>

<body>
<h1>Hi!</h1>
{%block index%}{%endblock%}

</body>
</html>